# Generated by Django 2.1.1 on 2019-11-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190916_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
