# Generated by Django 2.1.1 on 2019-11-27 02:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_auto_20191125_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hearts',
            field=models.ManyToManyField(blank=True, null=True, related_name='Post_hearts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='sads',
            field=models.ManyToManyField(blank=True, null=True, related_name='Post_sads', to=settings.AUTH_USER_MODEL),
        ),
    ]
